#!/bin/bash
function init_corepos() {
  corepos_list=
  if [ -e .corepos ]; then
    corepos_root=$PWD
    repo_path=$($GIT_EXEC_PATH/git config -f .corepos --get repo.path)
    if [ ! -z "$repo_path" ]; then
      for i in ${repo_path//\// }; do
        corepos_root=$(dirname $corepos_root)
      done
    else
      corepos_root=$(dirname $corepos_root)  # by default assume all repos are sibling directories
    fi
  fi
  corepos_list=$(grep "^\[repo " .corepos | tr -d '["]'"'" | tr  -s " " | cut -d" " -f2)
}

function init_repo_path() {
  repo_name=${1:?not set}
  repo_path=$($GIT_EXEC_PATH/git config -f .corepos --get repo.$repo_name.path)
  if [ -z "$repo_path" ]; then
    repo_path=$(dirname $PWD)/$repo_name
  else
    repo_path="${repo_path/\%repo/$repo_name}"
    repo_path="${repo_path/\%name/$repo_name}"
    repo_path="${repo_path/\%root\//}"
    [ "$repo_path" == "%root" ] && repo_path=$corepos_root
    repo_path="${repo_path//\/.\//\/}"
    [ "${repo_path:0:2}" == "~/" ] && repo_path="${HOME:?not set}${repo_path:1}"
    [ "${repo_path:0:1}" != "/" ] && repo_path=$corepos_root/$repo_path
  fi
}

function init_repo_status() {
  repo_path=${1:?not set}
  repo_error=
  repo_uncommitted=
  repo_commit=missing
  if [ -d $repo_path ]; then
    repo_commit=$(env -u GIT_INDEX_FILE -u GIT_PREFIX $GIT_EXEC_PATH/git -C $repo_path rev-parse --short=12 HEAD 2>&1)
    if [ $? != 0 ]; then
      repo_error="cannot get status: $repo_commit"
      repo_commit=unknown
    else
      repo_status=$(env -u GIT_INDEX_FILE -u GIT_PREFIX $GIT_EXEC_PATH/git -C $repo_path status --untracked-files=no --porcelain 2>&1)
      if [ $? != 0 ]; then
        repo_error="cannot get status: $repo_status"
      elif [ ! -z "$repo_status" ]; then
      # git status --short --ignore-submodules --untracked-files=no
      # $GIT_EXEC_PATH/git -C $repo_path diff # -index HEAD
      # [ $? != 0 ] &&
        repo_commit="$repo_commit+"
        repo_uncommitted="uncommitted changes:\n$repo_status"
      fi
    fi
  else
    repo_error="directory $repo_path is missing"
  fi
}